# Generated by Django 5.2.1 on 2025-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
