# Generated by Django 5.2.1 on 2025-07-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_vente_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='montant_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
